### ISSUE TITLE
Make table and body elements collapsible

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/afterman#11]
**Is your feature request related to a problem? Please describe.**
The API at startup does not need to show as much detail

**Describe the solution you'd like**

2 options (HTML)
1 - Inject javascript to add this feature
2 - Add a static javascript file that can be downloaded along with the main file

At Markdown I can't think how

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by itsalb3rt** [comment]
Added collacsible for table of content in HTML version

**Comment by Jadhielv** [comment]
I would like to help you with this @itsalb3rt
