### ISSUE TITLE
Hide empty cards when not data set

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/afterman#13]
**Is your feature request related to a problem? Please describe.**
Hide empty cards mark by red arrow

![image](https://user-images.githubusercontent.com/35310226/94494319-e86eff80-01bc-11eb-93b8-8f548cfa0c78.png)

**Describe the solution you'd like**
Check the data object for check if empty.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by lewandy** [comment]
Hey, I would like work this

**Comment by itsalb3rt** [comment]
@lewandy Wield your best weapon and face the monster!
