### ISSUE TITLE
Download in Markdown not function

### ISSUE THREAD

**Issue by Jadhielv** [itsalb3rt/afterman#16]
**Is your feature request related to a problem? Please describe.**
**Download in Markdown** not function when import a collection with multiple folders.

View Details:

![imagen](https://user-images.githubusercontent.com/24376900/96611604-d7e90b00-12ca-11eb-89ab-76adb882a9f1.png)

![imagen](https://user-images.githubusercontent.com/24376900/96611704-f18a5280-12ca-11eb-9d41-2c33409ae289.png)

**Describe the solution you'd like**
Apply fix according to what was discussed.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by itsalb3rt** [comment]
working...
