### ISSUE TITLE
 Cannot read property 'toString' of undefined" RequestBody.vue

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/afterman#21]
**Is your feature request related to a problem? Please describe.**
When import a collection with any request with empty body the console say:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'toString' of undefined"
```

**Describe the solution you'd like**
check if the function receives a string.

```javascript
    parseBody (body) {
      if (body) {
        return body.toString()
      }
      return ''
    },
```

**Describe alternatives you've considered**
Or

```javascript
    parseBody (body) {
      if (typeof body === 'string') {
        return body.toString()
      }
      return ''
    },
```

**Additional context**
NONE

**Comment by Jadhielv** [comment]
I would like to help you with this @itsalb3rt
